### PR TITLE
Fix the e2e prod script to avoid double creates and fakerp-esque deletes

### LINKED ISSUE #1622: RealRP tests create a cluster twice.
RealRP tests create a cluster twice. Once via "make config: in the hack/test/e2e-create-prod.sh, second via calls to azure client in the test spec itself.

### PR DESCRIPTION
**Pull request by charlesakalugwu**
- it doesnt need to call `make delete` because tests run against prod without access to kubeconfigs etc
- it doesnt need to call `make create` because the tests against the real rp already create a resource group and cluster as prereqs
- do not run the sanity package init logic if we are running a test against production TEST_IN_PRODUCTION=true

/cc @jim-minter @mjudeikis

```release-note
NONE
```

closes #1622

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
```
charles@titan:~/Documents/go/src/github.com/openshift/openshift-azure$ FOCUS='\[Vnet\]\[Real\]' hack/tests/e2e-create-prod.sh
=== RUN   TestE2E
e2e tests starting, git commit COMMIT
Running Suite: e2e tests
========================
Random Seed: 1557409107
Will run 1 of 31 specs

SSSSSSSSSSSSSS
------------------------------
Peer Vnet tests [Vnet][Real][LongRunning] 
  should create the vnet and cluster and verify peering
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/realrp/vnetpeering.go:48
configuring the real resource provider
time="2019-05-09T15:38:27+02:00" level=info msg="using region westeurope" func=github.com/openshift/openshift-azure/pkg/fakerp/client.NewConfig file="/home/charles/Documents/go/src/github.com/openshift/openshift-azure/pkg/fakerp/client/config.go:52"
STEP: creating a custom vnet
STEP: setting the custom vnet id in the osa request for peering
STEP: creating an OSA cluster
STEP: ensuring the OSA cluster vnet is peered with the custom vnet
STEP: deleting resource group charles-terraform
```

File: hack/tests/e2e-create-prod.sh [hunk 1]
```diff
@@ -22,6 +21,4 @@ trap cleanup EXIT
 export RUNNING_UNDER_TEST=false
 export TEST_IN_PRODUCTION=true
 
-make create
```
Comment (ehashman) [inline hack/tests/e2e-create-prod.sh]: If this test isn't being run against the RealRP, will the resource group needed be successfully created?

Comment (charlesakalugwu) [reply hack/tests/e2e-create-prod.sh]: The ginkgo tests against the real rp already have blocks to ensure resource group and cluster creation e.g.
```
BeforeEach(func() {
	var err error
	cli, err = azure.NewClientFromEnvironment(context.Background(), log.GetTestLogger(), false)
	Expect(err).NotTo(HaveOccurred())

	cfg, err = client.NewConfig(tlog.GetTestLogger())
	Expect(err).NotTo(HaveOccurred())

	// create a new resource group
	err = client.EnsureResourceGroup(cfg)
	Expect(err).ToNot(HaveOccurred())
})
```

Comment (ehashman) [reply hack/tests/e2e-create-prod.sh]: Ah, okay, I was missing that this script only targets the RealRP.

File: test/sanity/sanity.go [hunk 2]
```diff
@@ -16,21 +16,23 @@ import (
...
 
 func init() {
-	b, err := ioutil.ReadFile("../../_data/containerservice.yaml") // running via `go test`
-	if os.IsNotExist(err) {
-		b, err = ioutil.ReadFile("_data/containerservice.yaml") // running via compiled test binary
-	}
-	if err != nil {
-		panic(err)
-	}
+	if os.Getenv("TEST_IN_PRODUCTION") != "true" {
```
Comment (charlesakalugwu) [inline test/sanity/sanity.go]: i'm not very fond of this...

**Comment by charlesakalugwu** [comment]
flake #1628 
/retest

**Comment by ehashman** [comment]
@charlesakalugwu this needs a rebase

**Comment by charlesakalugwu** [comment]
> @charlesakalugwu this needs a rebase

thanks

**Comment by charlesakalugwu** [comment]
flake #1631

**Comment by charlesakalugwu** [comment]
flake #1631
/retest
