### PR TITLE
make IsMatchingSyscallError() more flexible

### LINKED ISSUE #1400: write: connection reset by peer talking to storage account
time="2019-04-02T00:37:12Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfgwdqw8oq44ss3x8eu4gd.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.16.144:44410->52.226.8.148:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"

### PR DESCRIPTION
**Pull request by asalkeld**
IsMatchingSyscallError() is currently not parsing a fully formatted url.Error. This PR makes this possible.

```release-note
NONE
```

closes #1400

### CODE REVIEW

**Comment by asalkeld** [comment]
flake #1438 
/test upgrade-v6.0

File: pkg/util/errors/errors.go [hunk 1]
```diff
@@ -26,11 +26,11 @@ var (
 )
 
 func unwrapNetHTTPError(err error) (bool, error) {
-	if !strings.HasPrefix(err.Error(), netHTTPErrorPrefix) {
+	if !strings.Contains(err.Error(), netHTTPErrorPrefix) {
 		return false, err
 	}
 	for sysMsg, errno := range str2Syscall {
-		if strings.Contains(err.Error()[netHTTPErrorPrefixLen:], sysMsg) {
+		if strings.Contains(err.Error(), sysMsg) {
```
Comment (charlesakalugwu) [inline pkg/util/errors/errors.go]: can you also remove the `netHTTPErrorPrefixLen` at the top of the file?

Comment (asalkeld) [reply pkg/util/errors/errors.go]: sure, forgot about that
