### PR TITLE
Unwrap "net/http: HTTP/1.x transport connection broken" error

### LINKED ISSUE #1400: write: connection reset by peer talking to storage account
time="2019-04-02T00:37:12Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfgwdqw8oq44ss3x8eu4gd.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.16.144:44410->52.226.8.148:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"

### PR DESCRIPTION
**Pull request by asalkeld**
```release-note
NONE
```
closes #1400

### CODE REVIEW

File: pkg/util/errors/errors.go [hunk 1]
```diff
@@ -4,17 +4,44 @@ import (
...
+
+// some common network errors that we check for
+var str2Syscall = map[string]syscall.Errno{
+	"connection reset by peer":  syscall.ECONNRESET,
+	"connection refused":        syscall.ECONNREFUSED,
+	"network is unreachable":    syscall.ENETUNREACH,
+	"no such file or directory": syscall.ENOENT,
+}
+
+func unwrapNetHTTPError(err error) (bool, error) {
```
Comment (mjudeikis) [inline pkg/util/errors/errors.go]: Any reason why `IsNetHTTPConnectionBrokenWrapperError` and `unwrapNetHTTPError` should not be in the same function? Considering they are very interconnected in the logic below? Or make `IsNetHTTPConnectionBrokenWrapperError` unexposed? as alone is not much of the value?

Comment (asalkeld) [reply pkg/util/errors/errors.go]: I can simplify it, it was just how I started off ... 
I'll get rid of IsNetHTTPConnectionBrokenWrapperError() and just add the check for net/http in the unwrap function.

**Comment by asalkeld** [comment]
flakes #1336

**Comment by asalkeld** [comment]
flake #1616

File: pkg/util/errors/errors.go [hunk 2]
```diff
@@ -4,17 +4,40 @@ import (
...
+	if !strings.HasPrefix(err.Error(), "net/http: HTTP/1.x transport connection broken:") {
```
Comment (charlesakalugwu) [inline pkg/util/errors/errors.go]: what do you think about extracting that string to a variable `foo` so we can use `len(foo)` below instead of 47?

File: pkg/util/errors/errors.go [hunk 3]
```diff
@@ -4,17 +4,40 @@ import (
...
+
 // IsMatchingSyscallError returns true when the error is one of the Errno's in match
 // it deals with the different ways of wrapping the syscalls.
 func IsMatchingSyscallError(err error, match ...syscall.Errno) bool {
 	for {
 		switch t := err.(type) {
+		case nil:
+			return false
 		case *azure.RequestError:
 			err = &t.DetailedError
```
Comment (charlesakalugwu) [inline pkg/util/errors/errors.go]: I really think you can save one iteration of the for loop in the case where this function is called with a `*azure.RequestError` by doing:

```suggestion
			err = t.DetailedError.Original
```

**Comment by thekad** [comment]
this LGTM

File: pkg/util/errors/errors.go [hunk 4]
```diff
@@ -4,17 +4,40 @@ import (
...
+	"network is unreachable":    syscall.ENETUNREACH,
+	"no such file or directory": syscall.ENOENT,
+}
+
+func unwrapNetHTTPError(err error) (bool, error) {
+	if !strings.HasPrefix(err.Error(), "net/http: HTTP/1.x transport connection broken:") {
+		return false, err
+	}
+	for sysMsg, errno := range str2Syscall {
+		if strings.Contains(err.Error()[47:], sysMsg) {
```
Comment (y-cote) [inline pkg/util/errors/errors.go]: Seems like
```
if strings.Contains(err.Error(), sysMsg) {
```
would be enough here since we assume the string will be constantly starting the same (HasPrefix) and doesn't conflict with the strings we compare with?

Comment (asalkeld) [reply pkg/util/errors/errors.go]: absolutely, I just wanted to save some searching time. if that is not worth it, i can remove it. it is in the error path so performance not really a priority

Comment (y-cote) [reply pkg/util/errors/errors.go]: that's right, clearer is better than faster here, but it's optional.

Comment (y-cote) [reply pkg/util/errors/errors.go]: /lgtm

Comment (asalkeld) [reply pkg/util/errors/errors.go]: i have cleaned it up a bit, i hope it's better to read now..
