### PR TITLE
fixing etcdbackup test

### LINKED ISSUE #1672: etcdbackuprecovery e2e failing
Etcdbackuprecovery failing on 404 in /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/etcdbackuprecovery.go:68

/kind test-flake

https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-etcdbackuprecovery/21/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-etcdbackuprecovery/22/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-etcdbackuprecovery/23/build-log.txt

### PR DESCRIPTION
**Pull request by Makdaam**
making sure the backup variable is initialized before each run.
If the name of the backup is empty, fakeRP returns 404.

Fixes #1672 

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/specs/fakerp/etcdbackuprecovery.go [hunk 1]
```diff
@@ -28,7 +28,9 @@ var _ = Describe("Etcd Recovery E2E tests [EtcdBackupRecovery][Fake][LongRunning
 	)
 
 	BeforeEach(func() {
-		backup, err := random.LowerCaseAlphanumericString(5)
+		var err error
+		// := can't be used below, because that redeclares "backup" in local scope
```
Comment (ehashman) [inline test/e2e/specs/fakerp/etcdbackuprecovery.go]: We could solve this by not mutating `backup = foo + backup` below maybe and calling it something else (like `backup_label`? Is that the bug?

Comment (Makdaam) [reply test/e2e/specs/fakerp/etcdbackuprecovery.go]: This will work too, and is cleaner :)
The bug is that there's var backup string declared in line 26, and using := declares a new backup string in the scope of BeforeEach func, so none of the init code has any effect on the value of "backup" in the rest of the code.
