### PR TITLE
Fix key rotation test

### LINKED ISSUE #971: key rotation test failure
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-azure-key-rotation-e2e/34
```
time="2019-01-03T13:09:40Z" level=info msg="draining infra-1546518200-000000"
time="2019-01-03T13:10:15Z" level=info msg="deleting infra-1546518200-000000"
time="2019-01-03T13:11:06Z" level=info msg="deleting scaleset ss-infra-1546518200"
time="2019-01-03T13:11:07Z" level=info msg="updating worker agent pool compute"
time="2019-01-03T13:11:07Z" level=info msg="found source scaleset ss-compute-1546518200"
time="2019-01-03T13:11:07Z" level=info msg="creating target scaleset ss-compute-1546518832"
time="2019-01-03T13:11:09Z" level=info msg="scaling ss-compute-1546518832 capacity up from 0 to 1"
time="2019-01-03T13:12:50Z" level=info msg="waiting for compute-1546518832-000000 to be ready"
time="2019-01-03T13:14:06Z" level=info msg="scaling ss-compute-1546518200 capacity down from 1 to 0"
time="2019-01-03T13:14:06Z" level=info msg="draining compute-1546518200-000000"
time="2019-01-03T13:14:13Z" level=info msg="deleting compute-1546518200-000000"
time="2019-01-03T13:16:45Z" level=info msg="deleting scaleset ss-compute-1546518200"
time="2019-01-03T13:16:56Z" level=info msg="waiting for infra services to be ready"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-node/sync"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-sdn/ovs"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-sdn/sdn"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset kube-service-catalog/apiserver"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset kube-service-catalog/controller-manager"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-template-service-broker/apiserver"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-azure-logging/mdsd"
time="2019-01-03T13:16:56Z" level=info msg="checking daemonset openshift-azure-logging/td-agent"
time="2019-01-03T13:16:56Z" level=info msg="checking statefulset openshift-infra/bootstrap-autoapprover"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment default/docker-registry"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment default/router"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment default/registry-console"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment openshift-infra/customer-admin-controller"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment openshift-ansible-service-broker/asb"
time="2019-01-03T13:16:56Z" level=info msg="checking deployment openshift-web-console/webconsole"
time="2019-01-03T13:16:57Z" level=info msg="checking deployment openshift-console/console"
time="2019-01-03T13:16:57Z" level=info msg="starting health check"
time="2019-01-03T13:16:57Z" level=info msg="checking console health"
time="2019-01-03T13:16:57Z" level=info msg=OK
STEP: Parsing the config blob after the update
STEP: Verifying that the initial config blob does not match the one created after the update
STEP: Verifying that the mutated config blob matches the one created after the update

• Failure [2591.893 seconds]
Key Rotation E2E tests [KeyRotation][Fake][LongRunning]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:22
  should be possible to maintain a healthy cluster after rotating all credentials [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:35

  Expected
      <bool>: false
  to be true

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:72
```
/kind bug
/assign @charlesakalugwu

### PR DESCRIPTION
**Pull request by charlesakalugwu**
closes #971 

/cc @kargakis @mjudeikis

### CODE REVIEW

File: test/clients/azure/client.go [hunk 1]
```diff
@@ -92,7 +92,7 @@ func NewClientFromEnvironment(setStorageClient bool) (*Client, error) {
 	rpc := externalapi.NewOpenShiftManagedClustersClientWithBaseURI(rpURL, subscriptionID)
 	rpc.Authorizer = authorizer
 
-	rpcAdmin := adminapi.NewOpenShiftManagedClustersClientWithBaseURI(rpURL, subscriptionID)
+	rpcAdmin := adminapi.NewOpenShiftManagedClustersClientWithBaseURI(rpURL+shared.AdminContext, subscriptionID)
```
Comment (kargakis) [inline test/clients/azure/client.go]: This is already set in the client.

File: pkg/fakerp/fakerp.go [hunk 2]
```diff
@@ -207,6 +207,16 @@ func writeHelpers(c *api.OpenShiftManagedCluster) error {
 	if err != nil {
 		return err
 	}
+	if _, err = os.Stat(filepath.Join(dataDir, "_out/id_rsa")); err == nil {
```
Comment (kargakis) [inline pkg/fakerp/fakerp.go]: It would be nice to add a comment on why we need to be storing the ssh twice.

**Comment by charlesakalugwu** [comment]
#560 

/test keyrotation

**Comment by charlesakalugwu** [comment]
#560 #850 

/test e2e

**Comment by charlesakalugwu** [comment]
#850 

/test e2e

**Comment by charlesakalugwu** [comment]
#982

File: test/e2e/specs/fakerp/keyrotation.go [hunk 3]
```diff
@@ -64,12 +64,35 @@ var _ = Describe("Key Rotation E2E tests [KeyRotation][Fake][LongRunning]", func
...
 		By("Verifying that the initial config blob does not match the one created after the update")
-		configMatch := reflect.DeepEqual(internal.Config.Certificates, internalAfterUpdate.Config.Certificates)
+		configMatch := reflect.DeepEqual(internal.Config.Certificates, updated.Config.Certificates)
 		Expect(configMatch).To(BeFalse())
 
-		By("Verifying that the mutated config blob matches the one created after the update")
-		configMatch = reflect.DeepEqual(mutated.Config.Certificates, internalAfterUpdate.Config.Certificates)
-		Expect(configMatch).To(BeTrue())
+		By("Verifying that the updated internal config blob and the config returned after the update contain matching ca certificates")
+		Expect(reflect.DeepEqual(internalAfterUpdate.Config.Certificates.ServiceSigningCa.Cert, updated.Config.Certificates.ServiceSigningCa.Cert)).To(BeTrue())
```
Comment (kargakis) [inline test/e2e/specs/fakerp/keyrotation.go]: Instead of comparing `updated` with `internalAfterUpdate`, a more honest check would be `updated` with `internal` and expect it to be false.

Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: Also, ensure you deep copy `internal` before mutating its state.

Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: Actually, the ideal test would minimize the amount of steps that deal with the internal config blob with the goal being to totally remove dealing with the internal config blob. Ideally, as an client-side admin test, you should GET the OSA resource, then do the key rotation RPC call, then compare the response with the result from GET.

Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: This can be improved in the future, I think there might be some work on making GET foolproof in the fake rp.

/lgtm

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/560

/retest

File: test/e2e/specs/fakerp/keyrotation.go (hunk 3 above)
Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: > This can be improved in the future, I think there might be some work on making GET foolproof in the fake rp.

Opened https://github.com/openshift/openshift-azure/pull/985
