### PR TITLE
Geneva key rotation action

### LINKED ISSUE #996: Key rotation fails with Invalid change for Properties.NetworkProfile.VnetID
The key rotation test fails with the following error: 

```
Expected error:
      <autorest.DetailedError>: {
          Original: {
              s: "autorest/azure: error response cannot be parsed: \"400 Bad Request: Failed to apply request: invalid change [Properties.NetworkProfile.VnetID: /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-kyrkbgyh/providers/Microsoft.Network/virtualNetworks/vnet != ]\\n\" error: json: cannot unmarshal number into Go value of type azure.RequestError",
          },
          PackageType: "containerservice.OpenShiftManagedClustersClient",
          Method: "CreateOrUpdate",
          StatusCode: 0,
          Message: "Failure sending request",
          ServiceError: nil,
          Response: nil,
      }
      containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: "400 Bad Request: Failed to apply request: invalid change [Properties.NetworkProfile.VnetID: /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-kyrkbgyh/providers/Microsoft.Network/virtualNetworks/vnet != ]\n" error: json: cannot unmarshal number into Go value of type azure.RequestError
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:57
------------------------------
S

Summarizing 1 Failure:
```

https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-key-rotation-e2e/39/build-log.txt

/cc @kargakis 
/kind bug
/assign

### PR DESCRIPTION
**Pull request by charlesakalugwu**
As part of AZURE-173, this PR adds key rotation functionality to the plugin.

closes #996 

/cc @jim-minter @kargakis

### CODE REVIEW

File: pkg/plugin/plugin_test.go [hunk 1]
```diff
@@ -256,3 +257,30 @@ func TestRecoverEtcdCluster(t *testing.T) {
...
+
+func TestRotateClusterSecrets(t *testing.T) {
+	mockCtrl := gomock.NewController(t)
+	defer mockCtrl.Finish()
+
+	mockGen := mock_config.NewMockGenerator(mockCtrl)
+	mockUp := mock_cluster.NewMockUpgrader(mockCtrl)
+	mockArm := mock_arm.NewMockGenerator(mockCtrl)
+
+	mockGen.EXPECT().InvalidateSecrets(nil).Return(nil)
```
Comment (kwoodson) [inline pkg/plugin/plugin_test.go]: How do these tests work?  Looks like this and the following are doing `nil` checks.  Just for my understanding.

File: pkg/api/admin/api/client.go [hunk 2]
```diff
@@ -410,6 +410,92 @@ func (client OpenShiftManagedClustersClient) RestoreResponder(resp *http.Respons
 	return
 }
 
+// RotateSecretsAndWait rotates the keys of an openshift managed cluster and waits
+// for the request to complete before returning.
+func (client OpenShiftManagedClustersClient) RotateSecretsAndWait(ctx context.Context, resourceGroupName, resourceName string, parameters OpenShiftManagedCluster) (result autorest.Response, err error) {
```
Comment (kargakis) [inline pkg/api/admin/api/client.go]: I don't think you need to pass `parameters`? It should be enough to send the rg and the resource name of the cluster that should have its secrets rotated.

File: pkg/plugin/plugin.go [hunk 3]
```diff
@@ -136,3 +136,40 @@ func (p *plugin) CreateOrUpdate(ctx context.Context, cs *api.OpenShiftManagedClu
...
 }
+
+func (p *plugin) RotateClusterSecrets(ctx context.Context, cs *api.OpenShiftManagedCluster, deployFn api.DeployFn, pluginTemplate *pluginapi.Config) *api.PluginError {
+	p.log.Info("invalidating non-ca certificates, private keys and secrets")
+	err := p.configGenerator.InvalidateSecrets(cs)
+	if err != nil {
+		return &api.PluginError{Err: err, Step: api.PluginStepInvalidateClusterSecrets}
+	}
+	p.log.Info("regenerating config including private keys and secrets")
+	err = p.GenerateConfig(ctx, cs, pluginTemplate)
```
Comment (kargakis) [inline pkg/plugin/plugin.go]: The rest of this is `p.CreateOrUpdate`, right?

File: test/e2e/specs/fakerp/keyrotation.go [hunk 4]
```diff
@@ -33,116 +24,50 @@ var _ = Describe("Key Rotation E2E tests [KeyRotation][Fake][LongRunning]", func
...
+		Expect(reflect.DeepEqual(before.Config.Certificates.OpenShiftMaster.Cert, after.Config.Certificates.OpenShiftMaster.Cert)).To(BeFalse())
+		Expect(reflect.DeepEqual(before.Config.Certificates.Registry.Cert, after.Config.Certificates.Registry.Cert)).To(BeFalse())
+		Expect(reflect.DeepEqual(before.Config.Certificates.Router.Cert, after.Config.Certificates.Router.Cert)).To(BeFalse())
+		Expect(reflect.DeepEqual(before.Config.Certificates.ServiceCatalogAPIClient.Cert, after.Config.Certificates.ServiceCatalogAPIClient.Cert)).To(BeFalse())
+		Expect(reflect.DeepEqual(before.Config.Certificates.ServiceCatalogServer.Cert, after.Config.Certificates.ServiceCatalogServer.Cert)).To(BeFalse())
+
+		// TODO: work towards moving the certs below to the updated section above
+		By("Verifying that certain non-ca public certificates have not been updated")
+		Expect(reflect.DeepEqual(before.Config.Certificates.GenevaLogging.Cert, after.Config.Certificates.GenevaLogging.Cert)).To(BeTrue())
+		Expect(reflect.DeepEqual(before.Config.Certificates.GenevaMetrics.Cert, after.Config.Certificates.GenevaMetrics.Cert)).To(BeTrue())
```
Comment (kargakis) [inline test/e2e/specs/fakerp/keyrotation.go]: You should also verify that nothing else has changed apart from the certificates.

File: test/e2e/specs/fakerp/keyrotation.go [hunk 5]
```diff
@@ -2,28 +2,19 @@ package fakerp
...
-	"github.com/openshift/openshift-azure/pkg/api"
-	fakerp "github.com/openshift/openshift-azure/pkg/fakerp/client"
-	"github.com/openshift/openshift-azure/pkg/util/managedcluster"
 	"github.com/openshift/openshift-azure/test/clients/azure"
 )
 
 var _ = Describe("Key Rotation E2E tests [KeyRotation][Fake][LongRunning]", func() {
 	var (
-		cli        *azure.Client
-		manifest   = flag.String("manifest", "../../_data/manifest.yaml", "Path to the manifest to send to the RP")
```
Comment (kargakis) [inline test/e2e/specs/fakerp/keyrotation.go]: You need to update the test requirements in parallel to this change.

**Comment by kargakis** [comment]
You also need to update validation to allow all secrets and certificates to be updated.

File: pkg/plugin/plugin.go (hunk 3 above)
Comment (charlesakalugwu) [reply pkg/plugin/plugin.go]: right

File: pkg/api/admin/api/client.go (hunk 2 above)
Comment (charlesakalugwu) [reply pkg/api/admin/api/client.go]: thats correct. i'll take parameters out.

File: test/e2e/specs/fakerp/keyrotation.go (hunk 5 above)
Comment (charlesakalugwu) [reply test/e2e/specs/fakerp/keyrotation.go]: ok

File: pkg/plugin/plugin_test.go (hunk 1 above)
Comment (charlesakalugwu) [reply pkg/plugin/plugin_test.go]: @kwoodson yes those look weird but those calls are setting up expectations and validating the order of calls in the tested function/method. I could also have done `mockGen.EXPECT().InvalidateSecrets(kenny).Return(nil)` and in this case, if the tested function is passed `kenny`, then I would expect that InvalidateSecrets(kenny) is called internally within that function and returns no error (nil).

I can have a call with you sometime to explain more about gomock

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (charlesakalugwu) [reply test/e2e/specs/fakerp/keyrotation.go]: Unfortunately `InvalidSecrets` doesn't only update certificates but certain secrets as well. 

```
c.RegistryHTTPSecret = nil
c.RegistryConsoleOAuthSecret = ""
c.ConsoleOAuthSecret = ""
c.AlertManagerProxySessionSecret = nil
c.AlertsProxySessionSecret = nil
c.PrometheusProxySessionSecret = nil
c.SessionSecretAuth = nil
c.SessionSecretEnc = nil
c.Images.GenevaImagePullSecret = nil
```

File: docs/e2e/requirements.md [hunk 6]
```diff
@@ -54,13 +54,3 @@ The following are required for running all e2e tests against the fake RP
 | `File` | `secrets/metrics-int.cert` | Geneva metrics client certificate |
 | `File` | `secrets/metrics-int.key` |  Geneva metrics client key |
 | `File` | `secrets/.dockerconfigjson` |  Docker config allowing to pull geneva images |
-
```
Comment (kargakis) [inline docs/e2e/requirements.md]: There is also two File entries that you need to update in L50 and L51

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: Right, but these fields are not accessible from the admin api. We probably need a different way to check that they actually get updated but I am not sure how this is going to look like for prod.

File: docs/e2e/requirements.md (hunk 6 above)
Comment (charlesakalugwu) [reply docs/e2e/requirements.md]: removed them

**Comment by charlesakalugwu** [comment]
FWIW I am consistently getting successful runs locally

```
charles@titan:~/Documents/go/src/github.com/openshift/openshift-azure$ make e2e-keyrotation 
FOCUS="\[KeyRotation\]\[Fake\]" TIMEOUT=70m ./hack/e2e.sh
bindata.go
bindata.go
=== RUN   TestE2E
e2e tests starting, git commit COMMIT
Running Suite: e2e tests
========================
Random Seed: 1547236650
Will run 1 of 32 specs

SS
------------------------------
Key Rotation E2E tests [KeyRotation][Fake][LongRunning] 
  should be possible to maintain a healthy cluster after rotating all credentials
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:26
configuring the fake resource provider
STEP: Reading the cluster state
INFO[2019-01-11T20:57:31+01:00] starting the fake resource provider          
INFO[2019-01-11T20:57:31+01:00] starting server on localhost:8080            
DEBU[2019-01-11T20:57:32+01:00] 127.0.0.1:45184 GET /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client) 
STEP: Executing key rotation on the cluster.
DEBU[2019-01-11T20:57:32+01:00] 127.0.0.1:45184 PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev/rotate/secrets?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client) 
INFO[2019-01-11T20:57:32+01:00] invalidating non-ca certificates, private keys and secrets 
INFO[2019-01-11T20:57:32+01:00] regenerating config including private keys and secrets 
INFO[2019-01-11T20:57:32+01:00] generating configs                           
INFO[2019-01-11T20:57:36+01:00] running CreateOrUpdate                       
INFO[2019-01-11T20:57:36+01:00] generating arm templates                     
INFO[2019-01-11T20:57:36+01:00] starting update                              
INFO[2019-01-11T20:57:36+01:00] applying arm template deployment             
INFO[2019-01-11T20:57:45+01:00] waiting for arm template deployment to complete 
INFO[2019-01-11T20:58:07+01:00] draining master-000000                       
INFO[2019-01-11T20:58:07+01:00] deallocating master-000000                   
INFO[2019-01-11T20:59:18+01:00] updating master-000000                       
INFO[2019-01-11T20:59:39+01:00] reimaging master-000000                      
INFO[2019-01-11T21:00:09+01:00] starting master-000000                       
INFO[2019-01-11T21:01:51+01:00] waiting for master-000000 to be ready        
INFO[2019-01-11T21:04:56+01:00] draining master-000001                       
INFO[2019-01-11T21:04:56+01:00] deallocating master-000001                   
INFO[2019-01-11T21:07:28+01:00] updating master-000001                       
INFO[2019-01-11T21:07:59+01:00] reimaging master-000001                      
INFO[2019-01-11T21:08:29+01:00] starting master-000001                       
INFO[2019-01-11T21:10:01+01:00] waiting for master-000001 to be ready        
INFO[2019-01-11T21:12:35+01:00] draining master-000002                       
INFO[2019-01-11T21:12:35+01:00] deallocating master-000002                   
INFO[2019-01-11T21:13:26+01:00] updating master-000002                       
INFO[2019-01-11T21:13:57+01:00] reimaging master-000002                      
INFO[2019-01-11T21:14:27+01:00] starting master-000002                       
INFO[2019-01-11T21:16:05+01:00] waiting for master-000002 to be ready        
INFO[2019-01-11T21:18:58+01:00] updating worker agent pool infra             
INFO[2019-01-11T21:18:59+01:00] found source scaleset ss-infra-1547232180    
INFO[2019-01-11T21:18:59+01:00] creating target scaleset ss-infra-1547236656 
INFO[2019-01-11T21:19:02+01:00] scaling ss-infra-1547236656 capacity up from 0 to 1 
INFO[2019-01-11T21:21:11+01:00] waiting for infra-1547236656-000000 to be ready 
INFO[2019-01-11T21:22:43+01:00] scaling ss-infra-1547232180 capacity down from 2 to 1 
INFO[2019-01-11T21:22:44+01:00] draining infra-1547232180-000001             
INFO[2019-01-11T21:22:57+01:00] deleting infra-1547232180-000001             
INFO[2019-01-11T21:25:19+01:00] scaling ss-infra-1547236656 capacity up from 1 to 2 
INFO[2019-01-11T21:27:28+01:00] waiting for infra-1547236656-000001 to be ready 
INFO[2019-01-11T21:28:55+01:00] scaling ss-infra-1547232180 capacity down from 1 to 0 
INFO[2019-01-11T21:28:55+01:00] draining infra-1547232180-000000             
INFO[2019-01-11T21:29:40+01:00] deleting infra-1547232180-000000             
INFO[2019-01-11T21:32:13+01:00] deleting scaleset ss-infra-1547232180        
INFO[2019-01-11T21:32:23+01:00] updating worker agent pool compute           
INFO[2019-01-11T21:32:24+01:00] found source scaleset ss-compute-1547232180  
INFO[2019-01-11T21:32:24+01:00] creating target scaleset ss-compute-1547236656 
INFO[2019-01-11T21:32:26+01:00] scaling ss-compute-1547236656 capacity up from 0 to 1 
INFO[2019-01-11T21:34:05+01:00] waiting for compute-1547236656-000000 to be ready 
INFO[2019-01-11T21:35:26+01:00] scaling ss-compute-1547232180 capacity down from 1 to 0 
INFO[2019-01-11T21:35:27+01:00] draining compute-1547232180-000000           
INFO[2019-01-11T21:35:27+01:00] deleting compute-1547232180-000000           
INFO[2019-01-11T21:36:28+01:00] deleting scaleset ss-compute-1547232180      
INFO[2019-01-11T21:36:39+01:00] waiting for infra services to be ready       
INFO[2019-01-11T21:36:39+01:00] checking daemonset default/docker-registry   
INFO[2019-01-11T21:36:39+01:00] checking daemonset default/router            
INFO[2019-01-11T21:36:39+01:00] checking daemonset openshift-node/sync       
INFO[2019-01-11T21:36:39+01:00] checking daemonset openshift-sdn/ovs         
INFO[2019-01-11T21:36:39+01:00] checking daemonset openshift-sdn/sdn         
INFO[2019-01-11T21:36:39+01:00] checking daemonset kube-service-catalog/apiserver 
INFO[2019-01-11T21:36:39+01:00] checking daemonset kube-service-catalog/controller-manager 
INFO[2019-01-11T21:36:39+01:00] checking daemonset openshift-template-service-broker/apiserver 
INFO[2019-01-11T21:36:39+01:00] checking daemonset openshift-azure-logging/mdsd 
INFO[2019-01-11T21:36:39+01:00] checking statefulset openshift-infra/bootstrap-autoapprover 
INFO[2019-01-11T21:36:39+01:00] checking deployment default/registry-console 
INFO[2019-01-11T21:36:39+01:00] checking deployment openshift-infra/customer-admin-controller 
INFO[2019-01-11T21:36:39+01:00] checking deployment openshift-ansible-service-broker/asb 
INFO[2019-01-11T21:36:39+01:00] checking deployment openshift-web-console/webconsole 
INFO[2019-01-11T21:36:39+01:00] checking deployment openshift-console/console 
INFO[2019-01-11T21:36:40+01:00] starting health check                        
INFO[2019-01-11T21:36:40+01:00] checking developer console health            
INFO[2019-01-11T21:36:40+01:00] checking admin console health                
INFO[2019-01-11T21:36:40+01:00] rotated cluster secrets                      
STEP: Reading the cluster state after the update
DEBU[2019-01-11T21:36:40+01:00] 127.0.0.1:45184 GET /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/charles-dev/providers/Microsoft.ContainerService/openShiftManagedClusters/charles-dev?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client) 
STEP: Verifying that ca certificates have not been updated
STEP: Verifying that certain non-ca public certificates have been updated
STEP: Verifying that certain non-ca public certificates have not been updated

• [SLOW TEST:2349.818 seconds]
Key Rotation E2E tests [KeyRotation][Fake][LongRunning]
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:15
  should be possible to maintain a healthy cluster after rotating all credentials
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:26
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 32 Specs in 2349.818 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 31 Skipped
--- PASS: TestE2E (2349.82s)
PASS
ok  	github.com/openshift/openshift-azure/test/e2e	2349.840s
signal: terminated
```

File: hack/e2e.sh [hunk 7]
```diff
@@ -19,6 +19,7 @@ if [[ "$FOCUS" == *"\[Fake\]"* ]]; then
     go generate ./...
     go run cmd/fakerp/main.go &
     trap 'return_id=$?; set +ex; kill $(lsof -t -i :8080); wait $(lsof -t -i :8080); exit $return_id' EXIT
+    while [[ "$(curl -s -o /dev/null -w '%{http_code}' localhost:8080)" == "000" ]]; do sleep 2; done
```
Comment (jim-minter) [inline hack/e2e.sh]: This is making something bad worse :-(
Remove this hunk and fix https://github.com/openshift/openshift-azure/issues/1036 in a separate PR.

File: pkg/config/generate.go [hunk 8]
```diff
@@ -477,3 +477,34 @@ func (g *simpleGenerator) Generate(cs *api.OpenShiftManagedCluster, template *pl
 
 	return
 }
+
+// InvalidateSecrets removes all non-ca certificates, private keys and secrets from an
+// OpenShiftManagedCluster's Config
+func (g *simpleGenerator) InvalidateSecrets(cs *api.OpenShiftManagedCluster) (err error) {
```
Comment (jim-minter) [inline pkg/config/generate.go]: I don't like that the top half of this function is whitelisting things to keep, and the bottom half is blacklisting things to reset.  I think that explicitly blacklisting things to reset is a better approach throughout.  WDYT?

There's also a separate question of how we keep this function updated when types change.  That's actually a very similar problem to how we keep the admin API updated when types change.  Can you open a topic in the architecture call document so we can discuss as a team?

File: pkg/config/generate_test.go [hunk 9]
```diff
@@ -134,3 +134,40 @@ func testRequiredFields(cs *api.OpenShiftManagedCluster, t *testing.T) {
 	assert(c.NodeBootstrapKubeconfig != nil, "NodeBootstrapKubeconfig")
 	assert(c.AzureClusterReaderKubeconfig != nil, "AzureClusterReaderKubeconfig")
 }
+
+func TestInvalidateSecrets(t *testing.T) {
+	dpc := &api.PluginConfig{}
```
Comment (jim-minter) [inline pkg/config/generate_test.go]: don't think you need dpc at all?  Remove and do `var g simpleGenerator` below?

File: pkg/config/generate_test.go [hunk 10]
```diff
@@ -134,3 +134,40 @@ func testRequiredFields(cs *api.OpenShiftManagedCluster, t *testing.T) {
...
+	populate.Walk(dpc, nil)
+	cs := &api.OpenShiftManagedCluster{}
+	populate.Walk(cs, nil)
+
+	g := &simpleGenerator{
+		pluginConfig: *dpc,
+	}
+	saved := *cs
```
Comment (jim-minter) [inline pkg/config/generate_test.go]: needs to be `saved := cs.DeepCopy()` for 2 reasons:
1) makes intent very clear
2) takes care of copying all the pointer objects (more robust)

File: pkg/config/generate_test.go [hunk 11]
```diff
@@ -134,3 +134,40 @@ func testRequiredFields(cs *api.OpenShiftManagedCluster, t *testing.T) {
...
+	if err := g.InvalidateSecrets(cs); err != nil {
+		t.Errorf("configGenerator.InvalidateSecrets error = %v", err)
+	}
+	if !reflect.DeepEqual(saved.Config, cs.Config) {
```
Comment (jim-minter) [inline pkg/config/generate_test.go]: This test feels pretty weak.  @kargakis @mjudeikis @asalkeld do you have any thoughts on how to strengthen it in a future proof way?

File: pkg/fakerp/rotatesecrets.go [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+	"context"
+	"fmt"
+	"net/http"
+
+	"github.com/openshift/openshift-azure/pkg/api"
+	"github.com/openshift/openshift-azure/pkg/plugin"
+)
+
+// handleRotateSecrets handles admin requests for the rotation of cluster secrets
+func (s *Server) handleRotateSecrets(w http.ResponseWriter, req *http.Request) {
```
Comment (jim-minter) [inline pkg/fakerp/rotatesecrets.go]: there's loads of copying of boilerplate here from handleRestore() - can you refactor so that it's DRY instead?

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (jim-minter) [reply test/e2e/specs/fakerp/keyrotation.go]: I feel like we should be doing all these Expect()s in the unit test.  Here in the e2e we should be testing that the cluster still actually works.

File: hack/e2e.sh (hunk 7 above)
Comment (kargakis) [reply hack/e2e.sh]: we should be adding these retries in the client inside go instead of here?

File: pkg/config/generate_test.go (hunk 11 above)
Comment (kargakis) [reply pkg/config/generate_test.go]: First compare all fields that are expected to be different then assign `saved` values back to those changed in `cs`, then expect `reflect.DeepEqual(saved.Config, cs.Config) == true`?

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: The healthcheck already runs as part of the rotate process. Anything more you would want to check? Maybe run e2e tests?

File: pkg/config/generate.go (hunk 8 above)
Comment (kargakis) [reply pkg/config/generate.go]: +1 on just blacklisting what needs to be updated

File: pkg/fakerp/middleware.go [hunk 13]
```diff
@@ -24,6 +24,10 @@ func (s *Server) validator(handler http.Handler) http.Handler {
 				http.Error(w, resp, http.StatusLocked)
 				return
 			}
+			defer func() {
```
Comment (kargakis) [inline pkg/fakerp/middleware.go]: This change is going to break blocking DELETEs and PUTs asynchronously.

File: docs/e2e/requirements.md [hunk 14]
```diff
@@ -47,20 +47,8 @@ The following are required for running all e2e tests against the fake RP
 | `Environment Variable` | `AZURE_TENANT_ID` | Required for authentication against the RP |
 | `Environment Variable` | `AZURE_SUBSCRIPTION_ID` | The subscription id for an existing cluster |
 | `Environment Variable` | `RESOURCEGROUP` | The resource group for an existing cluster |
-| `File` | `_data/containerservice.yaml` | Allows the test to retrieve credentials as well as to decide if it is a `create` vs `update` |
```
Comment (kargakis) [inline docs/e2e/requirements.md]: Unfortunately this file is still required for the openshift client setup. :/

File: pkg/config/generate_test.go (hunk 11 above)
Comment (mjudeikis) [reply pkg/config/generate_test.go]: I think we need to make sure we match all the changes and not changed values too. I think something under these lines 
as it was done here https://github.com/openshift/openshift-azure/blob/a22eecf16d8cb38d7bca600ef2de02143f3addba/pkg/api/types_test.go#L368 ?

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (mjudeikis) [reply test/e2e/specs/fakerp/keyrotation.go]: we might want to identify secret relationship to E2E test suit and make sure we test them like this

File: hack/e2e.sh (hunk 7 above)
Comment (jim-minter) [reply hack/e2e.sh]: Sorry, ignore my comment above - it was late and I read this wrong.  This isn't ideal but it's fine for now.

**Comment by charlesakalugwu** [comment]
key rotation was interrupted midway by a `connection time out` but the client retried the request, leading to the failure

```
Key Rotation E2E tests [KeyRotation][Fake][LongRunning] 
  should be possible to maintain a healthy cluster after rotating all credentials
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:26
configuring the fake resource provider
STEP: Reading the cluster state
time="2019-01-15T15:55:34Z" level=debug msg="127.0.0.1:35598 GET /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-knlnavrr/providers/Microsoft.ContainerService/openShiftManagedClusters/e2e-knlnavrr?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client)"
STEP: Executing key rotation on the cluster.
time="2019-01-15T15:55:34Z" level=debug msg="127.0.0.1:35598 PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-knlnavrr/providers/Microsoft.ContainerService/openShiftManagedClusters/e2e-knlnavrr/rotate/secrets?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client)"
time="2019-01-15T15:55:34Z" level=info msg="invalidating non-ca certificates, private keys and secrets"
time="2019-01-15T15:55:34Z" level=info msg="regenerating config including private keys and secrets"
time="2019-01-15T15:55:34Z" level=info msg="generating configs"
time="2019-01-15T15:55:38Z" level=info msg="running CreateOrUpdate"
time="2019-01-15T15:55:38Z" level=info msg="generating arm templates"
time="2019-01-15T15:55:38Z" level=info msg="starting update"
time="2019-01-15T15:55:38Z" level=info msg="applying arm template deployment"
time="2019-01-15T15:56:24Z" level=info msg="waiting for arm template deployment to complete"
time="2019-01-15T15:58:37Z" level=info msg="draining master-000000"
time="2019-01-15T15:58:37Z" level=info msg="deallocating master-000000"
time="2019-01-15T15:59:47Z" level=info msg="updating master-000000"
time="2019-01-15T16:00:18Z" level=info msg="reimaging master-000000"
time="2019-01-15T16:00:48Z" level=info msg="starting master-000000"
time="2019-01-15T16:04:20Z" level=info msg="waiting for master-000000 to be ready"
time="2019-01-15T16:20:03Z" level=debug msg="500 Internal Error: Failed to rotate cluster secrets: UpdateMasterAgentPoolWaitForReady: Get https://e2e-knlnavrr.eastus.cloudapp.azure.com/api/v1/nodes/master-000000: read tcp 172.16.83.189:33124->20.185.103.150:443: read: connection timed out"
time="2019-01-15T16:20:33Z" level=debug msg="127.0.0.1:54356 PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-knlnavrr/providers/Microsoft.ContainerService/openShiftManagedClusters/e2e-knlnavrr/rotate/secrets?api-version=admin (Go/go1.11.2 (amd64-linux) go-autorest/v10.15.4 openshift-azure/pkg/api/admin/api/client)"
time="2019-01-15T16:20:33Z" level=info msg="invalidating non-ca certificates, private keys and secrets"
time="2019-01-15T16:20:33Z" level=info msg="regenerating config including private keys and secrets"
time="2019-01-15T16:20:33Z" level=info msg="generating configs"
time="2019-01-15T16:20:40Z" level=info msg="running CreateOrUpdate"
time="2019-01-15T16:20:40Z" level=info msg="generating arm templates"
time="2019-01-15T16:20:40Z" level=info msg="starting update"
time="2019-01-15T16:20:40Z" level=info msg="applying arm template deployment"
time="2019-01-15T16:20:45Z" level=info msg="waiting for arm template deployment to complete"
time="2019-01-15T16:24:48Z" level=info msg="draining master-000000"
time="2019-01-15T16:24:49Z" level=info msg="deallocating master-000000"
time="2019-01-15T16:26:29Z" level=info msg="updating master-000000"
time="2019-01-15T16:27:10Z" level=info msg="reimaging master-000000"
time="2019-01-15T16:27:51Z" level=info msg="starting master-000000"
time="2019-01-15T16:29:42Z" level=info msg="waiting for master-000000 to be ready"
time="2019-01-15T16:32:52Z" level=info msg="draining master-000001"
```
artifacts: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/895/pull-ci-openshift-openshift-azure-master-e2e-azure-keyrotation/53/

#560 

/test keyrotation

File: pkg/fakerp/rotatesecrets.go (hunk 12 above)
Comment (charlesakalugwu) [reply pkg/fakerp/rotatesecrets.go]: I'll do this in a follow-up #1049

File: pkg/fakerp/middleware.go (hunk 13 above)
Comment (charlesakalugwu) [reply pkg/fakerp/middleware.go]: can you please elaborate how this breaks things?

Comment (kargakis) [reply pkg/fakerp/middleware.go]: When the request exits asynchronously, you release the lock too early while there is a background process that is actually running.

Comment (charlesakalugwu) [reply pkg/fakerp/middleware.go]: So essentially we will block accepting PUT or DELETE requests even when those requests are being handled asynchronously? This definitey sounds like a spot for improvement. 

On the other hand, without releasing the lock, spurious DELETE or PUT requests will block other requests e.g. if I make a PUT request to `/` that will block all legitimate PUT requests for resources from the RP.

Will need to rework this.

Comment (kargakis) [reply pkg/fakerp/middleware.go]: Yes, the current implementation does not account for managing different cluster deployments but that is probably a separate issue.

File: docs/e2e/requirements.md [hunk 15]
```diff
@@ -47,20 +47,9 @@ The following are required for running all e2e tests against the fake RP
...
-| `File` | `_data/manifest.yaml` | The external cluster manifest (required for key rotation and reentrant updates tests) |
+| `File` | `_data/containerservice.yaml` | Required for openshift client setup |
```
Comment (kargakis) [inline docs/e2e/requirements.md]: Not required anymore if you set `KUBECONFIG`.

File: docs/e2e/requirements.md [hunk 16]
```diff
@@ -47,20 +47,9 @@ The following are required for running all e2e tests against the fake RP
...
 | `File` | `secrets/logging-int.cert` | Geneva logging client certificate |
 | `File` | `secrets/logging-int.key` | Geneva logging client key |
 | `File` | `secrets/metrics-int.cert` | Geneva metrics client certificate |
 | `File` | `secrets/metrics-int.key` |  Geneva metrics client key |
 | `File` | `secrets/.dockerconfigjson` |  Docker config allowing to pull geneva images |
-
```
Comment (kargakis) [inline docs/e2e/requirements.md]: :tada:

File: pkg/config/generate_test.go [hunk 17]
```diff
@@ -134,3 +134,137 @@ func testRequiredFields(cs *api.OpenShiftManagedCluster, t *testing.T) {
...
+	cs.Config.Certificates.OpenShiftMaster = saved.Config.Certificates.OpenShiftMaster
+	cs.Config.Certificates.Registry = saved.Config.Certificates.Registry
+	cs.Config.Certificates.Router = saved.Config.Certificates.Router
+	cs.Config.Certificates.ServiceCatalogAPIClient = saved.Config.Certificates.ServiceCatalogAPIClient
+	cs.Config.Certificates.ServiceCatalogServer = saved.Config.Certificates.ServiceCatalogServer
+	cs.Config.Certificates.GenevaLogging = saved.Config.Certificates.GenevaLogging
+	cs.Config.Certificates.GenevaMetrics = saved.Config.Certificates.GenevaMetrics
+
+	// compare certs from saved and cs
+	if !reflect.DeepEqual(saved.Config.Certificates, cs.Config.Certificates) {
```
Comment (kargakis) [inline pkg/config/generate_test.go]: Should be  `!reflect.DeepEqual(saved.Config, cs.Config)`

File: pkg/fakerp/middleware.go (hunk 13 above)
Comment (kargakis) [reply pkg/fakerp/middleware.go]: Both CreateOrUpdate and Restore are synchronous and we don't block on deletes atm so this is ok for now.

File: test/e2e/specs/fakerp/keyrotation.go (hunk 4 above)
Comment (kargakis) [reply test/e2e/specs/fakerp/keyrotation.go]: Should be simpler to run our e2es
