### PR TITLE
don't output secret if validation fails

### LINKED ISSUE #1494: Update aad secret is returning to much information
When we tried to do an add secret update call on on an existing cluster, plugin is returning this :

```Errors found in validation of unversioned openshift cluster: [invalid change [Properties.AuthProfile.IdentityProviders.slice[0].Provider.Secret: a5ae9d91160da4bb7427- != 253351c2c5f0423f77b9;]]```

Secret should be hidden

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
* don't output secret if validation fails
```

fixes #1494

### CODE REVIEW

File: pkg/api/validate/api.go [hunk 1]
```diff
@@ -62,7 +62,15 @@ func (v *APIValidator) validateUpdateContainerService(cs, oldCs *api.OpenShiftMa
...
 
 	if !reflect.DeepEqual(cs, old) {
-		errs = append(errs, fmt.Errorf("invalid change %s", deep.Equal(cs, old)))
+		// TODO: this is a hack because we're using deep.Equal.  To fix properly
+		// we'd probably need to implement our own deep.Equal.
+		csCopy := cs.DeepCopy()
+		if csCopy.Properties.AuthProfile.IdentityProviders[0].Provider.(*api.AADIdentityProvider).Secret !=
+			old.Properties.AuthProfile.IdentityProviders[0].Provider.(*api.AADIdentityProvider).Secret {
+			csCopy.Properties.AuthProfile.IdentityProviders[0].Provider.(*api.AADIdentityProvider).Secret = "<hidden 1>"
+			old.Properties.AuthProfile.IdentityProviders[0].Provider.(*api.AADIdentityProvider).Secret = "<hidden 2>"
```
Comment (ehashman) [inline pkg/api/validate/api.go]: (note to self: mutating `old` is fine here because it's also a deep copy)
