### PR TITLE
Find core fakerp directories recursively

### LINKED ISSUE #826: Validation failed for resourceGroupName in dnsClient during cluster update
During a cluster update in e2e tests, validation fails for the resourcegroup name when the dnsClient tries to update zones. 

```
• Failure [4.580 seconds]
Key Rotation E2E tests [KeyRotation] [Fake] [LongRunning]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:25
  should be possible to maintain a healthy cluster after rotating all credentials [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:38

  Expected error:
      <validation.Error>: {
          PackageType: "dns.ZonesClient",
          Method: "CreateOrUpdate",
          Message: "autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value=\"\" details: value length must be greater than or equal to 1",
      }
      dns.ZonesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value="" details: value length must be greater than or equal to 1
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:75
------------------------------
SSSSSSSSSS
```

The dns client shouldn't run during updates. We need to investigate what's going on.

artifacts: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/794/pull-ci-openshift-openshift-azure-master-e2e-azure-keyrotation/18/

/cc mjudeikis 

/kind bug

### PR DESCRIPTION
**Pull request by charlesakalugwu**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it:**
To ensure that our fake rp works from either `cmd/createorupdate.go` or E2E tests in `test/e2e` we need to standardize how the fake rp finds the various core/config directories it needs for its operation. This PR introduces a function which allows a client to discover the absolute path to any named folder within the directory hierarchy of the caller. 

**Which issue(s) this PR fixes:**
Fixes #826 

**Release note:**
```
allow fake rp to find core/config directories recursively within its directory hierarchy
```

/cc @kargakis @mjudeikis

### CODE REVIEW

File: test/util/config/directory.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+	"path/filepath"
+)
+
+// FindDirectory returns the absolute path to a directory containing name within
+// the directory hierarchy of the caller. The search starts at the current working
+// directory of the caller
+func FindDirectory(name string) (string, error) {
+	current, err := os.Getwd()
+	if err != nil {
+		fmt.Printf("could not get working directory: %v\n", err)
```
Comment (kargakis) [inline test/util/config/directory.go]:
```go
return "", fmt.Errorf("could not get working directory: %v", err)
```

Comment (charlesakalugwu) [reply test/util/config/directory.go]: right :)

File: pkg/fakerp/config.go [hunk 2]
```diff
@@ -88,19 +91,23 @@ func GetPluginConfig() (*api.PluginConfig, error) {
...
+	logCert, err := readCert(path.Join(artifactDir, "logging-int.cert"))
 	if err != nil {
 		return nil, err
 	}
-	pullSecret, err := readFile(artifactDir + ".dockerconfigjson")
+	logKey, err := readKey(path.Join(artifactDir, "logging-int.key"))
 	if err != nil {
 		return nil, err
 	}
+	pullSecret, err := readFile(path.Join(artifactDir, ".dockerconfigjson"))
```
Comment (kargakis) [inline pkg/fakerp/config.go]: path.Join is not compatible with Windows, use filepath.Join

File: test/util/config/directory.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import (
+	"fmt"
+	"os"
+	"path/filepath"
+)
+
+// FindDirectory returns the absolute path to a directory containing name within
+// the directory hierarchy of the caller. The search starts at the current working
+// directory of the caller
+func FindDirectory(name string) (string, error) {
```
Comment (kargakis) [inline test/util/config/directory.go]: If we are planning on using this in production code, it should have unit tests.

Comment (mjudeikis) [reply test/util/config/directory.go]: I dont think we gonna use it in prod?

File: pkg/fakerp/config.go (hunk 2 above)
Comment (charlesakalugwu) [reply pkg/fakerp/config.go]: good to know

File: cmd/createorupdate/createorupdate.go [hunk 4]
```diff
@@ -21,6 +21,7 @@ import (
 	v20180930preview "github.com/openshift/openshift-azure/pkg/api/2018-09-30-preview/api"
 	"github.com/openshift/openshift-azure/pkg/fakerp"
 	"github.com/openshift/openshift-azure/pkg/util/azureclient"
+	"github.com/openshift/openshift-azure/test/util/config"
```
Comment (asalkeld) [inline cmd/createorupdate/createorupdate.go]: seems a little strange importing test modules from here

File: test/util/config/directory.go (hunk 3 above)
Comment (asalkeld) [reply test/util/config/directory.go]: also shouldn't this be in fakerp/config?

what about using something like this:
https://www.reddit.com/r/golang/comments/6ru4fw/finding_the_projects_root_directory/

func GetSecretsDir() string {
confDir := importPathToDir("github.com/openshift/openshift-azure/pkg/config") 
return path.Join(confDir, "..","..","secrets")
}

File: cmd/createorupdate/createorupdate.go (hunk 4 above)
Comment (mjudeikis) [reply cmd/createorupdate/createorupdate.go]: move to `utils/filepath/config.go` as it has a test already? @kargakis ?

File: test/util/config/directory.go [hunk 5]
```diff
@@ -0,0 +1,34 @@
+package config
```
Comment (kargakis) [inline test/util/config/directory.go]: Move these files in `pkg/fakerp` then you won't need to be importing them in a bunch of places.

File: cmd/createorupdate/createorupdate.go (hunk 4 above)
Comment (charlesakalugwu) [reply cmd/createorupdate/createorupdate.go]: the code has been moved to `pkg/fakerp`

File: test/util/config/directory.go (hunk 5 above)
Comment (charlesakalugwu) [reply test/util/config/directory.go]: done
