### PR TITLE
Retry Azure "GET" requests on connection reset by peer

### LINKED ISSUE #1592: storage.AccountsClient#ListByResourceGroup : connection reset by peer
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1589/pull-ci-azure-master-e2e-create/101

/kind test-flake

```

Openshift on Azure admin e2e tests [Fake][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/admin.go:23
  should be possible for an SRE to fetch the RP plugin version [It]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/admin.go:92

  Expected error:
      <autorest.DetailedError>: {
          Original: {
              Op: "Get",
              URL: "https://management.azure.com/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1589-e2e-create-bngjxx/providers/Microsoft.Storage/storageAccounts?api-version=2018-02-01",
              Err: {
                  Op: "read",
                  Net: "tcp",
                  Source: {
                      IP: [172, 16, 213, 117],
                      Port: 33442,
                      Zone: "",
                  },
                  Addr: {
                      IP: [13, 71, 185, 242],
                      Port: 443,
                      Zone: "",
                  },
                  Err: {Syscall: "read", Err: 0x68},
              },
          },
          PackageType: "storage.AccountsClient",
          Method: "ListByResourceGroup",
          StatusCode: 0,
          Message: "Failure sending request",
          ServiceError: nil,
          Response: nil,
      }
      storage.AccountsClient#ListByResourceGroup: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1589-e2e-create-bngjxx/providers/Microsoft.Storage/storageAccounts?api-version=2018-02-01: read tcp 172.16.213.117:33442->13.71.185.242:443: read: connection reset by peer
  not to have occurred
```

### PR DESCRIPTION
**Pull request by asalkeld**
closes #1592

```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
@asalkeld maybe start with something in retry.go that retries ECONNRESETs on GETs only and see where we get to?

**Comment by asalkeld** [comment]
> @asalkeld maybe start with something in retry.go that retries ECONNRESETs on GETs only and see where we get to?

done, ptal

File: pkg/util/azureclient/retry.go [hunk 1]
```diff
@@ -88,7 +91,11 @@ func (rs *retrySender) Do(req *http.Request) (resp *http.Response, err error) {
 	}
 }
 
-func isRetryableError(clientName string, err error) bool {
+func isRetryableError(clientName, method string, err error) bool {
+	if method == "GET" && errors.IsMatchingSyscallError(err, syscall.ECONNRESET) {
```
Comment (jim-minter) [inline pkg/util/azureclient/retry.go]: http.MethodGet preferred fwiw, but will lgtm anyway

Comment (jim-minter) [reply pkg/util/azureclient/retry.go]: @asalkeld I'm not convinced this would catch #1593 - that looks like the NetError is wrapped by a autorest.DetailedError.  I suppose you can update IsMatchingSyscallError to unwrap?

Comment (asalkeld) [reply pkg/util/azureclient/retry.go]: ok, i'll add the unwrapping to IsMatchingSyscallerrror so it can be reused.

File: pkg/util/errors/errors.go [hunk 2]
```diff
@@ -5,13 +5,20 @@ import (
...
+	"github.com/Azure/go-autorest/autorest/azure"
 )
 
 // IsMatchingSyscallError returns true when the error is one of the Errno's in match
 // it deals with the different ways of wrapping the syscalls.
 func IsMatchingSyscallError(err error, match ...syscall.Errno) bool {
 	for {
 		switch t := err.(type) {
+		case *azure.RequestError:
+			err = &t.DetailedError
```
Comment (charlesakalugwu) [inline pkg/util/errors/errors.go]: @asalkeld shouldn't this be `t.DetailedError.Original`?

Comment (asalkeld) [reply pkg/util/errors/errors.go]: it's caught in the line below
```
		case *autorest.DetailedError:
			err = t.Original
```
so that you can unwrap as many error combinations as possible.

File: pkg/util/errors/errors_test.go [hunk 3]
```diff
@@ -75,6 +78,28 @@ func TestIsMatchingSyscallError(t *testing.T) {
...
+			},
+		},
+		{
+			name:  "autorest detailed error : connection reset",
+			want:  true,
+			match: []syscall.Errno{syscall.ECONNRESET},
+			err: &autorest.DetailedError{
+				Original: os.NewSyscallError("io.read", syscall.ECONNRESET),
+			},
+		},
```
Comment (asalkeld) [inline pkg/util/errors/errors_test.go]: @charlesakalugwu you can see above i am testing both cases. DetailedError and RequestError
