### PR TITLE
Fix RefreshCluster validation for non-admin and fix openshift resolv.conf

### LINKED ISSUE #2144: Potential DNS mismatch between agent nodes
After a DNS settings update on the vnet. The vms need to be restarted to take the update. A user can scale the cluster with out using refresh cluster. The new vm will have the new dns settings while the rest of the cluster will have the old settings. Creating potential for inconsistent behavior in apps depending on which node they land on. If the dns settings have changed. All scale operations should be blocked until a refresh cluster has gone through.

### PR DESCRIPTION
**Pull request by asalkeld**
```release-note
Correct the behaviour of RefreshCluster when updating as non-admin
Correct the content of OpenShift resolve.conf
```
/cc @ehashman 

fixes #2144

### CODE REVIEW

File: pkg/plugin/plugin.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func (p *plugin) Validate(ctx context.Context, new, old *api.OpenShiftManagedClu
 		// don't call checkIfClusterWillRefresh() if we already have errors.
 		return
 	}
-	if !externalOnly && old != nil {
```
Comment (asalkeld) [inline pkg/plugin/plugin.go]: this was preventing the validation below as these 2 conditions never happen

File: pkg/startup/v14/data/master/etc/origin/node/resolv.conf [hunk 2]
```diff
@@ -1,3 +1,3 @@
-{{ range .Properties.NetworkProfile.Nameservers }}
+{{ range .ContainerService.Properties.NetworkProfile.Nameservers }}
```
Comment (asalkeld) [inline pkg/startup/v14/data/master/etc/origin/node/resolv.conf]: serious oops :-(

File: pkg/plugin/integration_test.go [hunk 3]
```diff
@@ -699,6 +699,30 @@ func TestHowActionsCauseRotations(t *testing.T) {
 		expectNodes    map[rotationType]int
 		expectCalls    []string
 	}{
+		{
+			name:           "scale up, with dns change",
+			expectRotation: map[rotationType]bool{rotationMaster: true, rotationInfra: true, rotationSync: false, rotationCompute: true},
```
Comment (asalkeld) [inline pkg/plugin/integration_test.go]: this test confirm that all nodes rotate

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (asalkeld) [reply pkg/plugin/plugin.go]: this needs some discussion as in the real rp clients don't exist in the first validate.

Comment (ehashman) [reply pkg/plugin/plugin.go]: Where did we land with this?

File: pkg/startup/v14/startup_test.go [hunk 4]
```diff
@@ -55,6 +57,34 @@ func TestFilePermissions(t *testing.T) {
...
+		Properties: api.Properties{
+			NetworkProfile: api.NetworkProfile{
+				Nameservers: []string{"1.2.3.4", "5.6.7.8"},
+			},
+		},
+	}
+	tmpl := `
+{{ range .ContainerService.Properties.NetworkProfile.Nameservers }}
+nameserver {{ . }}
+{{ end }}`
```
Comment (ehashman) [inline pkg/startup/v14/startup_test.go]: Is there any way to keep this in sync with the contents of `pkg/startup/v14/data/master/etc/origin/node/resolv.conf`? I'm worried that since this test is sort of unrelated they might drift. Can we read in the template from that file (or that of the current plugin) directly for the purposes of testing this?

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (asalkeld) [reply pkg/plugin/plugin.go]: i am changing it to (pending confirmation from Jack)
```
if !externalOnly && new.Properties.ProvisioningState != api.Creating {
```

File: pkg/startup/v14/startup_test.go (hunk 4 above)
Comment (asalkeld) [reply pkg/startup/v14/startup_test.go]: i'll just delete the test, it was just me confirming it was working

**Comment by asalkeld** [comment]
/retest
checkEnforcesEmptyDirQuotas failed
