### PR TITLE
manifest default was not working using envconfig

### LINKED ISSUE #756: upgrade test: failed parsing the manifest : open : no such file or directory
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure-upgrade/

/assign @asalkeld 
/kind bug

### PR DESCRIPTION
**Pull request by asalkeld**
fixes #756

### CODE REVIEW

File: pkg/fakerp/manifest.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func readEnv() map[string]string {
 func GenerateManifest(manifestFile string) (*sdk.OpenShiftManagedCluster, error) {
 	t, err := template.ParseFiles(manifestFile)
 	if err != nil {
-		return nil, errors.Wrapf(err, "failed parsing the manifest %s", manifestFile)
+		return nil, errors.Wrapf(err, "failed parsing the manifest \"%s\"", manifestFile)
```
Comment (kargakis) [inline pkg/fakerp/manifest.go]: %q
