### PR TITLE
retry when we get network errors

### LINKED ISSUE #1400: write: connection reset by peer talking to storage account
time="2019-04-02T00:37:12Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfgwdqw8oq44ss3x8eu4gd.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.16.144:44410->52.226.8.148:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"

### PR DESCRIPTION
**Pull request by asalkeld**
there is some inconsistent error handling for network errors, let's fix this up.

closes #1400

```release-note
NONE
```
/cc @jim-minter

### CODE REVIEW

File: pkg/util/ready/ready.go [hunk 1]
```diff
@@ -24,6 +29,30 @@ import (
 	apiregistrationv1client "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1"
 )
 
+// IsNetworkUnreachableError return true if this is a connection error
+func IsNetworkUnreachableError(err error) bool {
```
Comment (charlesakalugwu) [inline pkg/util/ready/ready.go]: The naming of this function is a little confusing to me ...especially with that check for the `x509.UnknownAuthorityError`. It might be worth having a look at how `go-autorest` does this in `isTemporaryNetworkError(err)`.

```
// returns true if the specified error is a temporary network error or false if it's not.
// if the error doesn't implement the net.Error interface the return value is true.
func isTemporaryNetworkError(err error) bool {
	if netErr, ok := err.(net.Error); !ok || (ok && netErr.Temporary()) {
		return true
	}
	return false
}
```

Comment (asalkeld) [reply pkg/util/ready/ready.go]: yip, i looked there, but want to  catch some more errors... maybe name it isRetryableError()?

Comment (charlesakalugwu) [reply pkg/util/ready/ready.go]: maybe `isRetryableConnectionError`?

File: pkg/cluster/initialize.go [hunk 2]
```diff
@@ -41,13 +44,24 @@ func (u *simpleUpgrader) writeBlob(blobName string, cs *api.OpenShiftManagedClus
...
 	json, err := json.Marshal(cs)
 	if err != nil {
 		return err
 	}
-
-	return b.CreateBlockBlobFromReader(bytes.NewReader(json), nil)
+	ctx := context.Background()
+	return wait.PollImmediateUntil(1*time.Second,
+		func() (bool, error) {
+			err = b.CreateBlockBlobFromReader(bytes.NewReader(json), nil)
```
Comment (jim-minter) [inline pkg/cluster/initialize.go]: can the retry somehow go into pkg/azureclient/storage so that the caller doesn't remember to have to do this?  this is how we handle it in the pkg/azureclient and in the kubeclient?

in the general case you'll need to do some magic so that you don't lose the contents of the reader if you get a network error half way through transmission (ugh)

File: pkg/cluster/kubeclient/ready.go [hunk 3]
```diff
@@ -56,6 +56,9 @@ func (u *kubeclient) WaitForReadySyncPod(ctx context.Context) error {
 					u.log.Info(err.ErrStatus.Details.Causes[0].Message)
 				}
 				return false, nil
+			case ready.IsNetworkUnreachableError(err):
```
Comment (jim-minter) [inline pkg/cluster/kubeclient/ready.go]: did you see this happen? should be dealt with 1 layer down in the kubeclient retryer

File: pkg/util/ready/ready.go (hunk 1 above)
Comment (jim-minter) [reply pkg/util/ready/ready.go]: I don't want to refactor the different error handling points into one, for several reasons:
* golang error nesting differs a lot and really hampers this approach over time
* we lose understanding of what errors are actually happening at each point and why

**Comment by asalkeld** [comment]
seems to be a problem with the change, investigating

File: pkg/util/azureclient/storage/storage.go [hunk 4]
```diff
@@ -93,3 +101,28 @@ type blob struct {
...
 
 var _ Blob = &blob{}
+
+func (b *blob) CreateBlockBlobFromReader(blob io.Reader, options *storage.PutBlobOptions) error {
+	ctx := context.Background()
+	data, err := ioutil.ReadAll(blob)
+	if err != nil {
+		return err
+	}
+	sr := io.NewSectionReader(bytes.NewReader(data), 0, int64(len(data)))
```
Comment (jim-minter) [inline pkg/util/azureclient/storage/storage.go]: can just use bytes.NewReader within the anonymous function below?

File: pkg/util/ready/ready.go [hunk 5]
```diff
@@ -24,6 +27,26 @@ import (
 	apiregistrationv1client "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1"
 )
 
+// IsMatchingSyscallError returns true when the error is one of the Errno's in match
+// it deals with the different ways of wrapping the syscalls.
+func IsMatchingSyscallError(err error, match []syscall.Errno) bool {
```
Comment (jim-minter) [inline pkg/util/ready/ready.go]: don't think pkg/util/ready is the right place for this - if nothing else, a new pkg/util/errors?
use `...syscall.Errno` instead of `[]syscall.Errno` to neaten up the call sites

File: pkg/util/ready/ready.go [hunk 6]
```diff
@@ -24,6 +27,26 @@ import (
...
+	switch t := err.(type) {
+	case *url.Error:
+		return IsMatchingSyscallError(t.Err, match)
```
Comment (jim-minter) [inline pkg/util/ready/ready.go]: I believe golang doesn't support tail recursion - use a loop here instead.  I know this is a bit of a nit, but recursing here might encourage others to do it in a place where it does matter.

File: pkg/util/ready/ready.go [hunk 7]
```diff
@@ -24,6 +27,26 @@ import (
...
+	case *os.SyscallError:
+		return IsMatchingSyscallError(t.Err, match)
+	case syscall.Errno:
+		for _, sc := range match {
+			if t == sc {
+				return true
+			}
+		}
+	}
```
Comment (jim-minter) [inline pkg/util/ready/ready.go]: I'm on the fence about adding a `default:` case + panic in the case of an unrecognised type - wdyt?

File: pkg/util/azureclient/storage/storage.go [hunk 8]
```diff
@@ -93,3 +101,28 @@ type blob struct {
...
+	return wait.PollImmediateUntil(2*time.Second,
```
Comment (jim-minter) [inline pkg/util/azureclient/storage/storage.go]: we are generally establishing a pattern why we try N times (3?) and log each failure.  Please do the same here.

File: pkg/util/ready/ready.go (hunk 5 above)
Comment (asalkeld) [reply pkg/util/ready/ready.go]: ok

File: pkg/util/azureclient/storage/storage.go (hunk 4 above)
Comment (asalkeld) [reply pkg/util/azureclient/storage/storage.go]: i'll try

File: pkg/util/ready/ready.go (hunk 7 above)
Comment (asalkeld) [reply pkg/util/ready/ready.go]: The point of the function is return true/false to "is this one of the syscall errors", so you can pass in
any error and you don't want to panic'ing, but rather returning false so that the caller can handle that
error differently.

File: pkg/util/azureclient/storage/storage.go (hunk 8 above)
Comment (asalkeld) [reply pkg/util/azureclient/storage/storage.go]: I remember why i didn't log, it's a long messy chain to pass the log variable into all the structs, but i can give it a go..

File: pkg/util/ready/ready.go (hunk 6 above)
Comment (asalkeld) [reply pkg/util/ready/ready.go]: ok, i'll change to a for loop

File: pkg/cluster/kubeclient/ready.go [hunk 9]
```diff
@@ -68,6 +70,9 @@ func (u *kubeclient) WaitForReadySyncPod(ctx context.Context) error {
 					u.log.Info(err.ErrStatus.Details.Causes[0].Message)
 				}
 				err = nil
+			case utilerrors.IsMatchingSyscallError(err, syscall.ECONNRESET):
```
Comment (jim-minter) [inline pkg/cluster/kubeclient/ready.go]: have you seen this error occur?  please can you share a link?

File: pkg/util/azureclient/storage/storage.go [hunk 10]
```diff
@@ -90,6 +112,27 @@ type Blob interface {
...
 
 var _ Blob = &blob{}
+
+func (b *blob) CreateBlockBlobFromReader(blob io.Reader, options *storage.PutBlobOptions) error {
+	ctx := context.Background()
+	data, err := ioutil.ReadAll(blob)
+	if err != nil {
+		return err
+	}
+	return wait.PollImmediateUntil(3*time.Second,
```
Comment (jim-minter) [inline pkg/util/azureclient/storage/storage.go]: this is not retrying 3 times, it is retrying indefinitely every 3 seconds.  Please follow the pattern in, e.g. `func (rs *retrySender) Do`

File: pkg/cluster/kubeclient/ready.go (hunk 9 above)
Comment (asalkeld) [reply pkg/cluster/kubeclient/ready.go]: https://github.com/openshift/openshift-azure/issues/1400#issuecomment-483920988
(should be connection refused, i'll update)

File: pkg/util/azureclient/storage/storage.go (hunk 10 above)
Comment (asalkeld) [reply pkg/util/azureclient/storage/storage.go]: ok, I agree about the retrying 3 times, but the retrySender.Do() seems to be at the wrong level (too lower level) as it is going to make resetting the Reader() impossible.

**Comment by asalkeld** [comment]
the error above was "quota exceeded"

**Comment by asalkeld** [comment]
flakes #1582 #1297 
/retest

**Comment by jim-minter** [comment]
pushed additional commit to use for loop instead of wait.PollImmediateUntil

/lgtm
